### ISSUE TITLE
Can not export or import, after generate a PIV Authentication Certificates

### ISSUE THREAD

**Issue by lcgogo** [Yubico/yubikey-manager-qt#264] opened 2021-03-08 10:17 UTC
I use the latest version 1.1.5 and yubikey 5C.
My Mac OS is 11.1 
MacBook Pro (15-inch, 2017)

After Select Applications --> PIV --> Certificates --> Authentication --> Generate a new one.
However, there is no response after I click Export icon.
The Delete icon can be used.
I also tried Import icon, useless too.

**Comment by fdennis** [comment] 2021-03-08 11:20
It is a problem with the latest version, 1.1.5b. It should work fine in 1.1.5 if you give that a go. This will be fixed in the next release.

**Comment by fdennis** [comment] 2021-03-08 11:21
You can find the releases here https://developers.yubico.com/yubikey-manager-qt/Releases/

**Comment by fdennis** [comment] 2021-03-08 11:25
On second thought, I'm reopening this issue and will instead close it when the next release is out.

**Comment by fdennis** [comment] 2021-03-16 13:40
This has been fixed in the latest version, 1.2.0. Please try it and reopen the issue if the problem is not solved.

**Closed by fdennis** 2021-03-16 13:40 UTC
