### ISSUE TITLE
Segmentation fault on Fedora package

### ISSUE THREAD

**Issue by DemiMarie** [Yubico/yubikey-manager-qt#252] opened 2020-12-14 00:00 UTC
This could just be a Fedora packaging bug, but I am reporting it here just in case.

When I start `ykman-gui`, I get this error:

```
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:30:13: Type Header unavailable
qrc:/qml/Header.qml:4:1: module "QtQuick.Dialogs" is not installed
Segmentation fault (core dumped)
```

**Comment by dainnilsson** [comment] 2021-01-08 13:15
Looks like a dupe of #182. I'd say that's a Fedora packaging bug, but at least there's a workaround until the package gets fixed!

**Closed by dainnilsson** 2021-01-08 13:15 UTC
