### ISSUE TITLE
YubiKey Manager is stuck on the "Insert your YubiKey" screen upon launch.

### ISSUE THREAD

**Issue by cwiemann** [Yubico/yubikey-manager-qt#194] opened 2019-08-07 01:58 UTC
Key is recognized as a USB device in System Report, but YubiKey Manager is stuck on the "Insert your YubiKey" screen upon launch.

(Yubico Authenticator is also stuck on "No YubiKey Detected" screen upon launch.)

**Comment by cwiemann** [comment] 2019-08-14 15:08
Mac OS 10.12.6 and Yubikey 4 OTP+U2F+CCID.

**Comment by ybaumy** [comment] 2019-08-22 16:23
with fedora 30 I have the same issue using the appimage version

**Comment by pcrockett** [comment] 2019-11-24 18:31
#197 might be a duplicate of this issue

**Closed** 2019-12-02 12:18 UTC

**Comment by teambates** [comment] 2020-04-17 08:45
Hi I have the same issue

I configured my Yubikey NFC with Gnupg on the terminal and I can access the device with authenticator. So not sure what the problem is.

I have installed lates Mac Version on High Sierra.
Any help welcome
