### ISSUE TITLE
Not possible to block PUK for PIV

### ISSUE THREAD

**Issue by oregano87** [Yubico/yubikey-manager-qt#173] opened 2019-03-05 15:34 UTC
In the older configuration tool "YubiKey PIV Manager" the PUK was blocked if the PIN was used as management key. This prevents that the PIN can simply be reset with the default PUK.
In the YubiKey Manager 1.1.0 you can see that the PUK is blocked if the YubiKey was initialized with the PIV Manager. But if the YubiKey is re-initialized with the YubiKey Manager (PIN and Management Key reassigned and Management Key protected with PIN), the default PUK is still valid. Even if it is entered wrong three times, the GUI does not indicate that the PUK is locked.

**Comment by dagheyman** [comment] 2019-03-06 08:16
Thanks for the report!

Most of this is by design, but I can understand that it can appear confusing.

The way YubiKey Manager and YubiKey PIV Manager implements 'Use PIN as Management Key" is slightly different.

PIV Manager derives the management key from the PIN (this is described [here](https://developers.yubico.com/yubikey-piv-manager/PIN_and_Management_Key.htm)). In this scheme the PUK is blocked, because if it was allowed to reset the PIN, the management key would be lost.

YubiKey Manager, and ykman, on the other hand instead generates a random management key and stores it on the device in a slot protected by the PIN. This offers some security benefits, as well as allowing us to keep the PUK functionality enabled. Unlocking the PIN with the PUK does not effect the management key, it's still stored on the device protected by the PIN.

YubiKey Manager is backwards compatible with devices initialized with the older YubiKey PIV Manager tool, and can recognize that the PUK is blocked in those cases. However, it is not possible to know if the PUK is blocked in the general case (the only way to know is to try to use it), which is why it's not normally shown in the GUI.

It is strongly recommended to always change the default PUK, regardless if you are using the "Use PIN as Management Key" or not. Maybe this could be emphasized more in the GUI and documentation.

**Comment by oregano87** [comment] 2019-03-06 10:32
Thank you for the quick reply and the detailed explanation.

Unfortunately, the new approach does not fit into our previous processes, as we deliberately did not want to set a PUK. If the PIN was entered wrong three times, the Yubikey had to be reinitialized. Therefore, we must now set a random PUK so that it is not possible to try the PIN any number of times with the default PUK. Maybe there is a way to implement the feature of a not usable PUK in any way.

One more question. You say that you can't check if the PUK is blocked or not. If you enter the PUK incorrectly three times, the GUI will not indicate that the PUK is blocked. If you then enter the PIN incorrectly three times, it will immediately indicate that both the PIN and the PUK are blocked. Therefore there should be a mechanism to check the status of the PUK. Otherwise the GUI might not show this, right?

**Comment by dagheyman** [comment] 2019-03-06 11:20
It is still possible to block the PUK, just enter the wrong one 3 times. The GUI will tell you after the last attempt that the PUK is now blocked. However, there is no way to tell that the PUK is blocked _without trying to use it_, which means that we can't show that information just when entering the PIV view in the GUI, since it would require us to try to use the PUK in the background.

**Comment by dagheyman** [comment] 2019-03-12 09:16
Closing this. Feel free to contact [Yubico Support](https://support.yubico.com/support/tickets/new), since they might have more bandwith to walk you through some of this if needed.

**Closed by dagheyman** 2019-03-12 09:16 UTC
