### ISSUE TITLE
Password and PIN prompted when importing certificates

### ISSUE THREAD

**Issue by oregano87** [Yubico/yubikey-manager-qt#175] opened 2019-03-12 10:04 UTC
If a certificate is imported (after generating a CSR) on the Yubikey, a password query appears first and then the query for the management key or alternatively for the PIN.

However, there is no password for a certificate, only for PKCS#12 files. Therefore the query for the password is unnecessary. It does not matter what password is entered.

**Comment by dagheyman** [comment] 2019-03-14 08:36
Thanks for the report!

I can't reproduce this. If the application can't parse either the certificate or the private key, it asks for a password and tries to decrypt the file with that. Could you provide an example certificate that triggers this behavior for you? Also make sure to test with the 1.1.1 release of the software.

**Comment by oregano87** [comment] 2019-03-14 10:39
I have now tested it with version 1.1.1, but the error happens again. I attached the certificate in both formats, PEM and DER.

[YubiKey_Test_Clientcert.zip](https://github.com/Yubico/yubikey-manager-qt/files/2965912/YubiKey_Test_Clientcert.zip)

**Comment by dagheyman** [comment] 2019-03-15 07:39
Thanks!

This is indeed a bug, but it only happens on windows. The parsing of the file fails because of how files are opened, and therefore it was handled as if it was encrypted by the GUI. A fix will be included in the next release.

**Closed** 2019-03-18 11:21 UTC
Labels: bug, windows
